# @baseUrl = https://wework-backend.onrender.com
@baseUrl = https://weworkbackend-production.up.railway.app


### 🧍‍♂️ Student sign-up
POST {{baseUrl}}/students/signup
Content-Type: application/json
Origin: http://localhost:5173


{
  "email": "olaoluwaoyetibo@gmail.com",
  "password": "Olaoluwa123-",
  "firstName": "John",
  "lastName": "Doe",
  "university": "State University",
  "major": "Computer Science",
  "graduationYear": "2026"
}


### 🔐 Student login (stores HttpOnly cookie)
POST {{baseUrl}}/students/login
Content-Type: application/json
Origin: http://localhost:5173

{
  "email": "john.doe@exam.com",
  "password": "StrongPassw0rd!"
}

### 👤 Get Profile (authenticated using saved cookie)
GET {{baseUrl}}/students/profile
Origin: http://localhost:5173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtaGNtNnNucTAwMDBnbzJtNm5wcnJvNXgiLCJlbWFpbCI6Im9sYW9sdXdhb3lldGlib0BnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJ1bml2ZXJzaXR5IjoiU3RhdGUgVW5pdmVyc2l0eSIsIm1ham9yIjoiQ29tcHV0ZXIgU2NpZW5jZSIsImdyYWR1YXRpb25ZZWFyIjoiMjAyNiIsInhwIjowLCJsZXZlbCI6MSwiY3JlYXRlZEF0IjoiMjAyNS0xMC0yOVQyMzoxNjoxMi41NjZaIiwiZW5yb2xsbWVudHMiOltdLCJyZXZpZXdzIjpbXSwicGF5bWVudHMiOltdLCJhcHBsaWNhdGlvbnMiOltdLCJwcm9ncmVzcyI6W10sImlhdCI6MTc2MTc4NDE4OSwiZXhwIjoxNzYyMzg4OTg5fQ.DmTuT4xQxvPL0mwHaFQwLc0XshsCwrDauA-6OdJx77Y

### 🚪 Logout (clears cookie)
POST {{baseUrl}}/students/logout


### ✏️ Update profile (still authenticated via cookie)
PATCH {{baseUrl}}/students/profile
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "university": "New University",
  "major": "Computer Science",
  "graduationYear": "2026",
  "email": "newemail@example.com"
}

### 👥 Get users
GET https://weworkbackend-production.up.railway.app/students

